name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.12
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
